spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/railway} # Usa el valor de la variable, con un valor por defecto para desarrollo local
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # dialect bajo properties.hibernate
    database: postgresql

# ... el resto de tu configuración

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  mailing:
    frontend:
      activation-url: ${FRONTEND_URL:http://localhost:4200}/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: ${PORT:8080}